/*
 * Copyright 2026, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.embedcode.gradle.report

/** Coordinates that identify the project described by the aggregate POM. */
internal data class PomCoordinates(
    val group: String,
    val artifact: String,
    val version: String,
)

/** A first-level external dependency and its representative Maven scope. */
internal data class PomDependency(
    val group: String,
    val artifact: String,
    val version: String,
    val scope: MavenScope,
)

/** Maven scope used to group dependencies in the generated report. */
internal enum class MavenScope(
    val xmlValue: String,
    val outputOrder: Int,
    val selectionOrder: Int,
) {
    COMPILE("compile", 0, 0),
    RUNTIME("runtime", 1, 1),
    TEST("test", 2, 3),
    PROVIDED("provided", 3, 2),
}

internal fun mavenScope(configurationName: String): MavenScope =
    when (configurationName) {
        "implementation",
        "api",
        ->
            MavenScope.COMPILE
        "runtimeOnly",
        "runtimeClasspath",
        "default",
        ->
            MavenScope.RUNTIME
        "compileOnly",
        "compileOnlyApi",
        "annotationProcessor",
        ->
            MavenScope.PROVIDED
        else -> {
            if (
                configurationName.startsWith("test", ignoreCase = true) ||
                    configurationName.startsWith("functionalTest", ignoreCase = true)
            ) {
                MavenScope.TEST
            } else {
                MavenScope.PROVIDED
            }
        }
    }

internal fun renderDependencyPom(
    coordinates: PomCoordinates,
    dependencies: List<PomDependency>,
): String =
    buildString {
        appendLine("""<?xml version="1.0" encoding="UTF-8"?>""")
        appendLine("""<project xmlns="http://maven.apache.org/POM/4.0.0"""")
        appendLine("""    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"""")
        appendLine(
            """    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 """ +
                """https://maven.apache.org/xsd/maven-4.0.0.xsd">""",
        )
        appendLine("  <modelVersion>4.0.0</modelVersion>")
        appendLine("  <!--")
        appendLine("    This file is generated by the `generateDependencyReports` Gradle task.")
        appendLine("    It documents first-level dependencies from all plugin-module")
        appendLine("    configurations and is not suitable for Maven build tasks.")
        appendLine("  -->")
        appendLine("  <groupId>${coordinates.group.escapeXml()}</groupId>")
        appendLine("  <artifactId>${coordinates.artifact.escapeXml()}</artifactId>")
        appendLine("  <version>${coordinates.version.escapeXml()}</version>")
        appendLine("  <licenses>")
        appendLine("    <license>")
        appendLine("      <name>The Apache License, Version 2.0</name>")
        appendLine("      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>")
        appendLine("      <distribution>repo</distribution>")
        appendLine("    </license>")
        appendLine("  </licenses>")
        appendLine("  <dependencies>")
        dependencies.forEach { dependency ->
            appendLine("    <dependency>")
            appendLine("      <groupId>${dependency.group.escapeXml()}</groupId>")
            appendLine("      <artifactId>${dependency.artifact.escapeXml()}</artifactId>")
            appendLine("      <version>${dependency.version.escapeXml()}</version>")
            appendLine("      <scope>${dependency.scope.xmlValue}</scope>")
            appendLine("    </dependency>")
        }
        appendLine("  </dependencies>")
        appendLine("</project>")
    }

private fun String.escapeXml(): String =
    replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&apos;")
