/*
 * Copyright 2026, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.embedcode.gradle.report

import com.github.jk1.license.LicenseReportExtension
import com.github.jk1.license.ModuleData
import com.github.jk1.license.ProjectData
import com.github.jk1.license.render.ReportRenderer
import java.io.File
import org.gradle.api.tasks.Input

/**
 * Renders the resolved dependency inventory as a Maven-shaped XML document.
 *
 * The result documents dependencies across project and build-script configurations. It is not a
 * Maven build descriptor.
 *
 * @property filename name of the generated report file.
 */
public class DependencyPomReportRenderer(
    @get:Input
    public val filename: String = "pom.xml",
) : ReportRenderer {

    /** Writes the dependency inventory collected by the license report plugin. */
    override fun render(data: ProjectData) {
        val extension = data.extension as LicenseReportExtension
        val outputFile = File(extension.absoluteOutputDir, filename)
        outputFile.writeText(renderPom(data))
    }

    private fun renderPom(data: ProjectData): String =
        buildString {
            appendLine("""<?xml version="1.0" encoding="UTF-8"?>""")
            appendLine(
                """<project xmlns="http://maven.apache.org/POM/4.0.0" """ +
                    """xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" """ +
                    """xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 """ +
                    """https://maven.apache.org/xsd/maven-4.0.0.xsd">""",
            )
            appendLine("  <modelVersion>4.0.0</modelVersion>")
            appendLine("  <!--")
            appendLine("    Generated by the `generateDependencyReports` Gradle task.")
            appendLine(
                "    This file documents resolved dependencies and is not a Maven build " +
                    "descriptor.",
            )
            appendLine("  -->")
            appendLine("  <groupId>${data.project.group.xmlEscape()}</groupId>")
            appendLine("  <artifactId>${data.project.name.xmlEscape()}</artifactId>")
            appendLine("  <version>${data.project.version.xmlEscape()}</version>")
            appendLine("  <dependencies>")
            data.allDependencies
                .distinctBy { Triple(it.group, it.name, it.version) }
                .sortedWith(
                    compareBy<ModuleData>(
                        { it.group.orEmpty() },
                        { it.name.orEmpty() },
                        { it.version.orEmpty() },
                    ),
                ).forEach { dependency ->
                    appendLine("    <dependency>")
                    appendLine("      <groupId>${dependency.group.xmlEscape()}</groupId>")
                    appendLine("      <artifactId>${dependency.name.xmlEscape()}</artifactId>")
                    appendLine("      <version>${dependency.version.xmlEscape()}</version>")
                    appendLine("    </dependency>")
                }
            appendLine("  </dependencies>")
            appendLine("</project>")
        }

    private fun Any?.xmlEscape(): String =
        toString()
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
}
