name: Check

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Java 17 for Compatibility Tests
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Set Up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build :gradle-plugin:publishToMavenLocal
