name: Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build :gradle-plugin:publishToMavenLocal
